#!/bin/bash

PURPLE='\033[1;35m'
GREEN='\033[0;32m'
ENDCOLOR='\033[0m'

function printSuccess {
    echo -e "${GREEN}Done! Happy prototyping! 🎉${ENDCOLOR}"
    echo
}

function revealInFinder {
read -r -d '' REVEAL_SCRIPT << EOS
    set playgroundPath to POSIX file "$1"
    tell application "Finder" to reveal playgroundPath
    tell application "Finder" to activate
EOS

    osascript -e "${REVEAL_SCRIPT}" > /dev/null 2>&1
}

# THE ICLOUD DRIVE DIRECTORY, USED BY PLAYGROUNDS ON IPAD
DRIVE_PATH=~/Library/Mobile\ Documents/iCloud\~com\~apple\~Playgrounds/Documents

# THIS IS OUR TEMPORARY WORKING DIRECTORY
TEMP_PATH=~/Library/Caches/ImagineEnginePlaygrounds

# CREATE TEMP DIR IF IT DOESN'T EXIST
if [ ! -d $TEMP_PATH ]; then
	mkdir -p $TEMP_PATH
fi

# NAME FOR THE WORKSPACE DIRECTORY
WORKSPACE_DIR_NAME="playground.xcworkspace"

# NAME FOR THE WORKSPACE DATA FILE
WORKSPACE_DATA_FNAME="contents.xcworkspacedata"

# CONTENTS FOR THE contents.xcworkspacedata FILE
read -r -d '' WORKSPACE_DATA << EOF
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
   <FileRef
      location = "self:">
   </FileRef>
</Workspace>
EOF

# NAME FOR THE PLAYGROUND DATA FILE
PLAYGROUND_DATA_FNAME="contents.xcplayground"

# CONTENTS FOR THE contents.xcplayground FILE
read -r -d '' PLAYGROUND_DATA << EOF
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<playground version='5.0' target-platform='ios'>
    <timeline fileName='timeline.xctimeline'/>
</playground>
EOF

# NAME FOR THE SOURCES DIRECTORY
SOURCES_DIR_NAME="Sources"

read -r -d '' MAIN_CONTENTS << EOF
//   
//   Generated by ImagineEngine
//   https://github.com/JohnSundell/ImagineEngine
//   Have fun!
//   
import UIKit

// Here's to the crazy ones...

EOF

echo
echo "Hi, I'm here to help you create a playground for you to play with Imagine Engine. Let's get started :-)"
echo

echo -e "${PURPLE}What do you want to call your playground? Example: MyCoolGame${ENDCOLOR}"
read PLAYGROUND_NAME

echo

echo "Generating..."
echo

PLAYGROUND_PATH="${TEMP_PATH}/${PLAYGROUND_NAME}.playground"

mkdir -p ${PLAYGROUND_PATH}

WORKSPACE_PATH="${PLAYGROUND_PATH}/${WORKSPACE_DIR_NAME}"

mkdir -p ${WORKSPACE_PATH}

SOURCES_PATH="${PLAYGROUND_PATH}/${SOURCES_DIR_NAME}"

mkdir -p ${SOURCES_PATH}

MAIN_PATH="${PLAYGROUND_PATH}/Contents.swift"
PLAYGROUND_DATA_PATH="${PLAYGROUND_PATH}/${PLAYGROUND_DATA_FNAME}"

WORKSPACE_DATA_PATH="${WORKSPACE_PATH}/${WORKSPACE_DATA_FNAME}"

echo "${MAIN_CONTENTS}" > ${MAIN_PATH}

echo "${PLAYGROUND_DATA}" > ${PLAYGROUND_DATA_PATH}

echo "${WORKSPACE_DATA}" > ${WORKSPACE_DATA_PATH}

# COPY SOURCE FILES TO THE SOURCES FOLDER

rsync -aP --exclude=*macOS* --exclude=AppKit ./Sources/* ${SOURCES_PATH} > /dev/null 2>&1

if [ -d "${DRIVE_PATH}" ]; then

    # ICLOUD DRIVE FOLDER EXISTS, OFFER TO COPY PLAYGROUND THERE
    echo -e "${PURPLE}Do you want to move the playground to iCloud drive so you can use it on your iPad? [Y/N] ${ENDCOLOR}"
    read -n 1 -r
    echo

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        # YES, MOVE TO ICLOUD DRIVE
        mv "${PLAYGROUND_PATH}" "${DRIVE_PATH}"

        echo
        echo -e "${GREEN}Done! The file is now on iCloud Drive and should appear in Swift Playgrounds on your iPad 🎉${ENDCOLOR}"
        echo
    else
        # NO, DO NOT MOVE (JUST REVEAL IN FINDER THEN)
        revealInFinder "${PLAYGROUND_PATH}"

        printSuccess
    fi

else

    # ICLOUD DRIVE FOLDER DOESN'T EXIST, REVEAL IN FINDER
    revealInFinder "${PLAYGROUND_PATH}"

    printSuccess

fi

